version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backstage
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/